### PR TITLE
Update .env.example

### PR DESCRIPTION
**Pull request by Jieiku**
Add some additional information regarding BIND_TO, DOMAIN, and SESSIONID_DOMAIN.

Make information succinct.

A couple options here are new that will be available in @matclab new SMTP pull request.

He said the pull request looks good but asked that I submit this pull request here instead of to his repository.

### CODE REVIEW

**Comment by ryanmcgrath** [comment]
The clarity on comments is appreciated, think this just needs to be rebased with regards to matclab's work. Otherwise down to merge.

**Comment by Jieiku** [comment]
ill do it now just to be sure, 1 sec

**Comment by Jieiku** [comment]
Good to go!

**Comment by ryanmcgrath** [comment]
Done~. Appreciate it!

**Pull request merged**
