### PR TITLE
Add email send test

### PR DESCRIPTION
**Pull request by matclab**
Add test for postmark and sendgrid email send api call with the help of httmock crate.
Correctly detect and report any API error for sendgrid and postmark.

This PR  relies on #19.

### CODE REVIEW

**Comment by matclab** [comment]
Hmmm, the PR starts from trunk instead of 1f589a0 but I do not know how to do that.

**Comment by Jieiku** [comment]
me either, I think you need @matclab to start merging these in, they seem ready to go!

**Comment by ryanmcgrath** [comment]
I think you might need to rebase this @matclab now that the other PR is merged in. Otherwise down to merge it.

**Comment by matclab** [comment]
PR rebased…

**Comment by ryanmcgrath** [comment]
Merged! Much appreciated as always.

**Pull request merged**
